before:
  hooks:
    - go mod tidy
    - go generate ./...
builds:
  - id: livekit
    env:
      - CGO_ENABLED=0
    main: ./cmd/server
    binary: livekit-server
    goarm:
      - "7"
    goarch:
      - amd64
      - arm64
      - arm
    goos:
      - linux
      - windows
archives:
  - format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
release:
  github:
    owner: livekit
    name: livekit
  draft: true
  prerelease: auto
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
gomod:
  proxy: true
  mod: mod
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"

